[project]
name = "my-fast-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = ["apps/userservice", "packages/utils"]

[tool.uv]
publish-url = "https://packages.aliyun.com/6a34d461d8362ae2652485c2/pypi/repo-fhghq"

[[tool.uv.index]]
name = "aliyun"
url = "https://packages.aliyun.com/6a34d461d8362ae2652485c2/pypi/repo-fhghq"
priority = "primary"

[[tool.uv.index]]
name = "mirror"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "default"
